# Generated by Django 3.0.3 on 2020-03-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logotip',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes'),
        ),
    ]
