# Generated by Django 3.0.3 on 2020-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200303_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
    ]
