# Generated by Django 3.0.3 on 2020-03-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_pessoa_apelido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='caixa_postal',
            new_name='caixapostal',
        ),
    ]
