# Generated by Django 3.0.3 on 2020-03-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20200306_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='caixapostal',
            new_name='caixa_postal',
        ),
    ]
