# Generated by Django 3.0.3 on 2020-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200306_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereço',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
