# Generated by Django 3.0.3 on 2020-03-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200310_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereço',
            name='cep',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Empresa'),
        ),
    ]
